Repository Gachon-Vigilante/Retriever_SpringBoot, pull requests merged in 2025-07, with the labels that each got.

#2 [Docs] PR & Issue 템플릿 생성
  .github/ISSUE_TEMPLATE/♻️_refactor.md
  .github/ISSUE_TEMPLATE/⚙️_chore.md
  .github/ISSUE_TEMPLATE/⚡_performance.md
  .github/ISSUE_TEMPLATE/✨_feature.md
  .github/ISSUE_TEMPLATE/🐛_bug.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#4 [Feature] User Document 설계
  src/main/java/com/team7/retriever/RetrieverApplication.java
  src/main/java/com/team7/retriever/entity/User.java
  src/main/java/com/team7/retriever/entity/enums/Role.java
Labels: ✨ feature

#6 [Feature] JWT 기반 인증 시스템 구축
  build.gradle
  src/main/java/com/team7/retriever/auth/cookie/CookieProvider.java
  src/main/java/com/team7/retriever/auth/jwt/exception/TokenErrorCode.java
  src/main/java/com/team7/retriever/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/team7/retriever/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/team7/retriever/auth/jwt/provider/JwtValidationType.java
  src/main/java/com/team7/retriever/auth/jwt/repository/TokenRepository.java
  src/main/java/com/team7/retriever/auth/jwt/service/TokenService.java
  src/main/java/com/team7/retriever/auth/redis/Token.java
  src/main/java/com/team7/retriever/auth/security/AdminAuthentication.java
  src/main/java/com/team7/retriever/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/team7/retriever/auth/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/team7/retriever/auth/security/MemberAuthentication.java
  src/main/java/com/team7/retriever/config/AuthConfig.java
  src/main/java/com/team7/retriever/config/RedisConfig.java
  src/main/java/com/team7/retriever/config/SecurityConfig.java
  src/main/java/com/team7/retriever/config/SwaggerConfig.java
  src/main/java/com/team7/retriever/config/WebConfig.java
  src/main/java/com/team7/retriever/controller/AuthController.java
  src/main/java/com/team7/retriever/dto/request/GrantRequest.java
  src/main/java/com/team7/retriever/dto/request/LoginRequest.java
  src/main/java/com/team7/retriever/dto/request/SignUpRequest.java
  src/main/java/com/team7/retriever/dto/response/LoginResponse.java
  src/main/java/com/team7/retriever/dto/response/LoginSuccessResponse.java
  src/main/java/com/team7/retriever/dto/response/ReissueResponse.java
  src/main/java/com/team7/retriever/entity/User.java
  src/main/java/com/team7/retriever/entity/enums/Role.java
  src/main/java/com/team7/retriever/exception/BadRequestException.java
  src/main/java/com/team7/retriever/exception/ConflictException.java
  src/main/java/com/team7/retriever/exception/CustomException.java
  src/main/java/com/team7/retriever/exception/ForbiddenException.java
  src/main/java/com/team7/retriever/exception/NotFoundException.java
  src/main/java/com/team7/retriever/exception/UnauthorizedException.java
  src/main/java/com/team7/retriever/exception/UserErrorCode.java
  src/main/java/com/team7/retriever/exception/base/BaseErrorCode.java
  src/main/java/com/team7/retriever/exception/base/BaseSuccessCode.java
  src/main/java/com/team7/retriever/handler/GlobalExceptionHandler.java
  src/main/java/com/team7/retriever/handler/dto/ErrorResponse.java
  src/main/java/com/team7/retriever/handler/dto/SuccessResponse.java
  src/main/java/com/team7/retriever/repository/UserRepository.java
  src/main/java/com/team7/retriever/service/AuthService.java
  src/main/resources/application.properties.example
Labels: ✨ feature

#8 [Refactor] 회원가입 방식 변경
  src/main/java/com/team7/retriever/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/team7/retriever/auth/jwt/service/TokenService.java
  src/main/java/com/team7/retriever/config/SecurityConfig.java
  src/main/java/com/team7/retriever/controller/AuthController.java
  src/main/java/com/team7/retriever/controller/UserController.java
  src/main/java/com/team7/retriever/dto/request/GrantRequest.java
  src/main/java/com/team7/retriever/dto/response/UserInfoResponse.java
  src/main/java/com/team7/retriever/entity/User.java
  src/main/java/com/team7/retriever/entity/enums/Role.java
  src/main/java/com/team7/retriever/exception/UserErrorCode.java
  src/main/java/com/team7/retriever/service/AuthService.java
  src/main/java/com/team7/retriever/service/UserService.java
Labels: ♻️ refactor, ✨ feature

#12 [Feature] Neo4j 데이터 조회 기능 추가
  src/main/java/com/team7/retriever/neo4j/controller/ArgotController.java
  src/main/java/com/team7/retriever/neo4j/controller/ChannelController.java
  src/main/java/com/team7/retriever/neo4j/controller/DrugController.java
  src/main/java/com/team7/retriever/neo4j/controller/PostController.java
  src/main/java/com/team7/retriever/neo4j/entity/Argot.java
  src/main/java/com/team7/retriever/neo4j/entity/Channel.java
  src/main/java/com/team7/retriever/neo4j/entity/Drug.java
  src/main/java/com/team7/retriever/neo4j/entity/Post.java
  src/main/java/com/team7/retriever/neo4j/entity/Posts.java
  src/main/java/com/team7/retriever/neo4j/entity/Promotes.java
  src/main/java/com/team7/retriever/neo4j/repository/NeoArgotRepository.java
  src/main/java/com/team7/retriever/neo4j/repository/NeoChannelRepository.java
  src/main/java/com/team7/retriever/neo4j/repository/NeoDrugRepository.java
  src/main/java/com/team7/retriever/neo4j/repository/NeoPostsRepository.java
  src/main/java/com/team7/retriever/neo4j/service/ArgotService.java
  src/main/java/com/team7/retriever/neo4j/service/ChannelService.java
  src/main/java/com/team7/retriever/neo4j/service/DrugService.java
  src/main/java/com/team7/retriever/neo4j/service/PostService.java
  src/main/java/com/team7/retriever/neo4j/service/SavingPromotionService.java
Labels: ✨ feature

#17 [Chore]️ CD 파이프라인 구축
  .github/workflows/cd.yml
  src/main/resources/application.properties.example
Labels: ⚙️ chore

#19 [Bug] 삭제한 사용 API 복원
  src/main/java/com/team7/retriever/domain/agrot/controller/ArgotsController.java
  src/main/java/com/team7/retriever/domain/agrot/service/ArgotsService.java
  src/main/java/com/team7/retriever/domain/drug/controller/DrugsController.java
  src/main/java/com/team7/retriever/domain/drug/service/DrugsService.java
Labels: 🐛 bug

#21 [Refactor] 전체 게시글 조회 기능에 pagination 추가
  src/main/java/com/team7/retriever/domain/bookmark/controller/BookmarksController.java
  src/main/java/com/team7/retriever/domain/bookmark/controller/dto/request/BookmarksRequest.java
  src/main/java/com/team7/retriever/domain/bookmark/domain/document/Bookmarks.java
  src/main/java/com/team7/retriever/domain/bookmark/domain/repository/BookmarksRepository.java
  src/main/java/com/team7/retriever/domain/bookmark/service/BookmarksService.java
  src/main/java/com/team7/retriever/domain/post/controller/PostsController.java
  src/main/java/com/team7/retriever/domain/post/controller/dto/response/PostPageResponse.java
  src/main/java/com/team7/retriever/domain/post/service/PostsService.java
Labels: ♻️ refactor
